# IAR Build Tools for Arm on GitLab CI/CD

# This workflow will run when a push is made to any branch in the repository
 
build-library:
  image: ghcr.io/iarsystems/arm:9.60.4-st
  stage: .pre 
  only:
    - branches
  needs: []
  script:
    - echo "Build library..."
    - iarbuild ./project/EWARM/ChecksumLibrary.ewp -make Debug -log all
  artifacts:
    paths:
      - project/EWARM/Debug/Exe/ChecksumLibrary.a
    expire_in: 1 week

cstat-library:
  image: ghcr.io/iarsystems/arm:9.60.4-st
  stage: build
  only:
    - branches
  needs: ["build-library"]
  script:
    - echo "Analyzing library..."
    - iarbuild project/EWARM/ChecksumLibrary.ewp -cstat_analyze Debug -log all
    - iarbuild project/EWARM/ChecksumLibrary.ewp -cstat_report Debug -log all
  artifacts:
    paths:
      - project/EWARM/Debug/C-STAT/*.html
    expire_in: 1 week  

build-project:
  image: ghcr.io/iarsystems/arm:9.60.4-st
  stage: build
  only:
    - branches
  needs: ["build-library"]
  script:
    - echo "Building project..."
    - iarbuild project/EWARM/project.ewp -make Debug -log all
  artifacts:
    paths:
      - project/EWARM/Debug/Exe/project.out

cstat-project:
  image: ghcr.io/iarsystems/arm:9.60.4-st
  stage: build
  only:
    - branches
  needs: ["build-project"]
  script:
    - echo "Analyzing project..."
    - iarbuild project/EWARM/project.ewp -cstat_analyze Debug -log all
    - iarbuild project/EWARM/project.ewp -cstat_report Debug -log all
  artifacts:
    paths:
      - project/EWARM/Debug/C-STAT/*.html
    expire_in: 1 week
